class Signals:
    LATCH_TOS_ARG = "latch tos number"
    LATCH_TOS_MEM_OUT = "latch tos mem out"
    LATCH_TOS_FROM_ALU = "latch tos alu out"
    LATCH_TOS_FROM_STACK = "latch tos from stack"
    LATCH_TOS_FROM_PC = "latch tos from pc"
    LATCH_TOS_INPUT = "latch tos input"
    LATCH_TOS_BR = "latch tos br"
    LATCH_ADDR_ARG = "latch addr number"
    LATCH_ADDR_FROM_MEM = "latch addr from mem"
    LATCH_ADDR_TOS = "latch addr tos"

    PC_NEXT = "pc next"
    PC_JUMP = "pc jump"
    PC_JZ = "pc jz"
    PC_RS = "pc rs"
